package Application;
// Generated Jun 19, 2017 11:42:59 AM by Hibernate Tools 4.3.1



/**
 * Cuenta generated by hbm2java
 */
public class Cuenta  implements java.io.Serializable {


     private Integer idCuenta;
     private String nickname;
     private String pass;
     private String tipoCuenta;

    public Cuenta() {
    }

    public Cuenta(String nickname, String pass, String tipoCuenta) {
       this.nickname = nickname;
       this.pass = pass;
       this.tipoCuenta = tipoCuenta;
    }
   
    public Integer getIdCuenta() {
        return this.idCuenta;
    }
    
    public void setIdCuenta(Integer idCuenta) {
        this.idCuenta = idCuenta;
    }
    public String getNickname() {
        return this.nickname;
    }
    
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getTipoCuenta() {
        return this.tipoCuenta;
    }
    
    public void setTipoCuenta(String tipoCuenta) {
        this.tipoCuenta = tipoCuenta;
    }




}


