package Application;
// Generated Jun 19, 2017 11:42:59 AM by Hibernate Tools 4.3.1



/**
 * DetallePrestamo generated by hbm2java
 */
public class DetallePrestamo  implements java.io.Serializable {


     private Integer idDetalle;
     private Integer cantidad;
     private int idArticulo;
     private int idPrestamo;

    public DetallePrestamo() {
    }

	
    public DetallePrestamo(int idArticulo, int idPrestamo) {
        this.idArticulo = idArticulo;
        this.idPrestamo = idPrestamo;
    }
    public DetallePrestamo(Integer cantidad, int idArticulo, int idPrestamo) {
       this.cantidad = cantidad;
       this.idArticulo = idArticulo;
       this.idPrestamo = idPrestamo;
    }
   
    public Integer getIdDetalle() {
        return this.idDetalle;
    }
    
    public void setIdDetalle(Integer idDetalle) {
        this.idDetalle = idDetalle;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public int getIdArticulo() {
        return this.idArticulo;
    }
    
    public void setIdArticulo(int idArticulo) {
        this.idArticulo = idArticulo;
    }
    public int getIdPrestamo() {
        return this.idPrestamo;
    }
    
    public void setIdPrestamo(int idPrestamo) {
        this.idPrestamo = idPrestamo;
    }




}


