package Application;
// Generated Jun 19, 2017 11:42:59 AM by Hibernate Tools 4.3.1



/**
 * ParticipantesProyectos generated by hbm2java
 */
public class ParticipantesProyectos  implements java.io.Serializable {


     private Integer idParticipante;
     private int idUsuario;
     private Integer idProyecto;

    public ParticipantesProyectos() {
    }

	
    public ParticipantesProyectos(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public ParticipantesProyectos(int idUsuario, Integer idProyecto) {
       this.idUsuario = idUsuario;
       this.idProyecto = idProyecto;
    }
   
    public Integer getIdParticipante() {
        return this.idParticipante;
    }
    
    public void setIdParticipante(Integer idParticipante) {
        this.idParticipante = idParticipante;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Integer getIdProyecto() {
        return this.idProyecto;
    }
    
    public void setIdProyecto(Integer idProyecto) {
        this.idProyecto = idProyecto;
    }




}


