package Application;
// Generated Jun 19, 2017 11:42:59 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Prestamo generated by hbm2java
 */
public class Prestamo  implements java.io.Serializable {


     private Integer idPrestamo;
     private Date fechaInicio;
     private Date fechaTermino;
     private boolean estado;
     private int idSolicitante;
     private int idEncargado;

    public Prestamo() {
    }

    public Prestamo(Date fechaInicio, Date fechaTermino, boolean estado, int idSolicitante, int idEncargado) {
       this.fechaInicio = fechaInicio;
       this.fechaTermino = fechaTermino;
       this.estado = estado;
       this.idSolicitante = idSolicitante;
       this.idEncargado = idEncargado;
    }
   
    public Integer getIdPrestamo() {
        return this.idPrestamo;
    }
    
    public void setIdPrestamo(Integer idPrestamo) {
        this.idPrestamo = idPrestamo;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaTermino() {
        return this.fechaTermino;
    }
    
    public void setFechaTermino(Date fechaTermino) {
        this.fechaTermino = fechaTermino;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public int getIdSolicitante() {
        return this.idSolicitante;
    }
    
    public void setIdSolicitante(int idSolicitante) {
        this.idSolicitante = idSolicitante;
    }
    public int getIdEncargado() {
        return this.idEncargado;
    }
    
    public void setIdEncargado(int idEncargado) {
        this.idEncargado = idEncargado;
    }




}


