package Application;
// Generated Jun 19, 2017 11:42:59 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto  implements java.io.Serializable {


     private Integer idProyecto;
     private String nombre;
     private String descripcion;
     private Date fechaInicio;
     private boolean estado;
     private int idJefe;

    public Proyecto() {
    }

	
    public Proyecto(String nombre, Date fechaInicio, boolean estado, int idJefe) {
        this.nombre = nombre;
        this.fechaInicio = fechaInicio;
        this.estado = estado;
        this.idJefe = idJefe;
    }
    public Proyecto(String nombre, String descripcion, Date fechaInicio, boolean estado, int idJefe) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.fechaInicio = fechaInicio;
       this.estado = estado;
       this.idJefe = idJefe;
    }
   
    public Integer getIdProyecto() {
        return this.idProyecto;
    }
    
    public void setIdProyecto(Integer idProyecto) {
        this.idProyecto = idProyecto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public int getIdJefe() {
        return this.idJefe;
    }
    
    public void setIdJefe(int idJefe) {
        this.idJefe = idJefe;
    }




}


