package cl.model.pojos;
// Generated 19-06-2017 18:14:24 by Hibernate Tools 4.3.1



/**
 * Articulo generated by hbm2java
 */
public class Articulo  implements java.io.Serializable {


     private Integer idArticulo;
     private String nombre;
     private String descripcion;
     private String observacion;
     private String marca;
     private String modelo;
     private String numeroSerie;
     private boolean estado;
     private int idTrack;

    public Articulo() {
    }

	
    public Articulo(String nombre, String descripcion, boolean estado, int idTrack) {
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.estado = estado;
        this.idTrack = idTrack;
    }
    public Articulo(String nombre, String descripcion, String observacion, String marca, String modelo, String numeroSerie, boolean estado, int idTrack) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.observacion = observacion;
       this.marca = marca;
       this.modelo = modelo;
       this.numeroSerie = numeroSerie;
       this.estado = estado;
       this.idTrack = idTrack;
    }
   
    public Integer getIdArticulo() {
        return this.idArticulo;
    }
    
    public void setIdArticulo(Integer idArticulo) {
        this.idArticulo = idArticulo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getNumeroSerie() {
        return this.numeroSerie;
    }
    
    public void setNumeroSerie(String numeroSerie) {
        this.numeroSerie = numeroSerie;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public int getIdTrack() {
        return this.idTrack;
    }
    
    public void setIdTrack(int idTrack) {
        this.idTrack = idTrack;
    }




}


