package cl.model.pojos;
// Generated 19-06-2017 18:14:24 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Boletin generated by hbm2java
 */
public class Boletin  implements java.io.Serializable {


     private Integer idBoletin;
     private String titulo;
     private String descripcion;
     private Date fecha;
     private boolean estado;
     private Integer idAutor;

    public Boletin() {
    }

	
    public Boletin(String titulo, String descripcion, Date fecha, boolean estado) {
        this.titulo = titulo;
        this.descripcion = descripcion;
        this.fecha = fecha;
        this.estado = estado;
    }
    public Boletin(String titulo, String descripcion, Date fecha, boolean estado, Integer idAutor) {
       this.titulo = titulo;
       this.descripcion = descripcion;
       this.fecha = fecha;
       this.estado = estado;
       this.idAutor = idAutor;
    }
   
    public Integer getIdBoletin() {
        return this.idBoletin;
    }
    
    public void setIdBoletin(Integer idBoletin) {
        this.idBoletin = idBoletin;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Integer getIdAutor() {
        return this.idAutor;
    }
    
    public void setIdAutor(Integer idAutor) {
        this.idAutor = idAutor;
    }




}


