package cl.model.pojos;
// Generated 19-06-2017 18:14:24 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Prestamo generated by hbm2java
 */
public class Prestamo  implements java.io.Serializable {


     private Integer idPrestamo;
     private Date fechaInicio;
     private Date fechaTermino;
     private Boolean estado;
     private String rutSolicitante;
     private String nombreSolicitante;
     private String apellidosSolicitante;
     private int idEncargado;

    public Prestamo() {
    }

	
    public Prestamo(Date fechaInicio, Date fechaTermino, String rutSolicitante, String nombreSolicitante, String apellidosSolicitante, int idEncargado) {
        this.fechaInicio = fechaInicio;
        this.fechaTermino = fechaTermino;
        this.rutSolicitante = rutSolicitante;
        this.nombreSolicitante = nombreSolicitante;
        this.apellidosSolicitante = apellidosSolicitante;
        this.idEncargado = idEncargado;
    }
    public Prestamo(Date fechaInicio, Date fechaTermino, Boolean estado, String rutSolicitante, String nombreSolicitante, String apellidosSolicitante, int idEncargado) {
       this.fechaInicio = fechaInicio;
       this.fechaTermino = fechaTermino;
       this.estado = estado;
       this.rutSolicitante = rutSolicitante;
       this.nombreSolicitante = nombreSolicitante;
       this.apellidosSolicitante = apellidosSolicitante;
       this.idEncargado = idEncargado;
    }
   
    public Integer getIdPrestamo() {
        return this.idPrestamo;
    }
    
    public void setIdPrestamo(Integer idPrestamo) {
        this.idPrestamo = idPrestamo;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaTermino() {
        return this.fechaTermino;
    }
    
    public void setFechaTermino(Date fechaTermino) {
        this.fechaTermino = fechaTermino;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getRutSolicitante() {
        return this.rutSolicitante;
    }
    
    public void setRutSolicitante(String rutSolicitante) {
        this.rutSolicitante = rutSolicitante;
    }
    public String getNombreSolicitante() {
        return this.nombreSolicitante;
    }
    
    public void setNombreSolicitante(String nombreSolicitante) {
        this.nombreSolicitante = nombreSolicitante;
    }
    public String getApellidosSolicitante() {
        return this.apellidosSolicitante;
    }
    
    public void setApellidosSolicitante(String apellidosSolicitante) {
        this.apellidosSolicitante = apellidosSolicitante;
    }
    public int getIdEncargado() {
        return this.idEncargado;
    }
    
    public void setIdEncargado(int idEncargado) {
        this.idEncargado = idEncargado;
    }




}


