package cl.model.pojos;
// Generated 19-06-2017 18:14:24 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String rut;
     private String nombre;
     private String apellidos;
     private int idCuenta;
     private int idCarrera;
     private int idTrack;

    public Usuario() {
    }

    public Usuario(String rut, String nombre, String apellidos, int idCuenta, int idCarrera, int idTrack) {
       this.rut = rut;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.idCuenta = idCuenta;
       this.idCarrera = idCarrera;
       this.idTrack = idTrack;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getRut() {
        return this.rut;
    }
    
    public void setRut(String rut) {
        this.rut = rut;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public int getIdCuenta() {
        return this.idCuenta;
    }
    
    public void setIdCuenta(int idCuenta) {
        this.idCuenta = idCuenta;
    }
    public int getIdCarrera() {
        return this.idCarrera;
    }
    
    public void setIdCarrera(int idCarrera) {
        this.idCarrera = idCarrera;
    }
    public int getIdTrack() {
        return this.idTrack;
    }
    
    public void setIdTrack(int idTrack) {
        this.idTrack = idTrack;
    }




}


